// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SourceCodeSummariser;

#nullable disable

namespace SourceCodeSummariser.Migrations
{
    [DbContext(typeof(SummaryContext))]
    partial class SummaryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SourceCodeSummariser.FileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("SourceCodeSummariser.MemberEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("BLOB");

                    b.Property<int>("FileEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileEntityId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("SourceCodeSummariser.MemberTagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TagId");

                    b.HasIndex("MemberId", "TagId")
                        .IsUnique();

                    b.ToTable("MemberTags");
                });

            modelBuilder.Entity("SourceCodeSummariser.TagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Category")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("SourceCodeSummariser.MemberEntity", b =>
                {
                    b.HasOne("SourceCodeSummariser.FileEntity", "File")
                        .WithMany("Members")
                        .HasForeignKey("FileEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("SourceCodeSummariser.MemberTagEntity", b =>
                {
                    b.HasOne("SourceCodeSummariser.MemberEntity", "Member")
                        .WithMany("MemberTags")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SourceCodeSummariser.TagEntity", "Tag")
                        .WithMany("MemberTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SourceCodeSummariser.FileEntity", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("SourceCodeSummariser.MemberEntity", b =>
                {
                    b.Navigation("MemberTags");
                });

            modelBuilder.Entity("SourceCodeSummariser.TagEntity", b =>
                {
                    b.Navigation("MemberTags");
                });
#pragma warning restore 612, 618
        }
    }
}
