import * as vscode from 'vscode';
import { DatabaseService } from './databaseService';

export class SummaryHoverProvider implements vscode.HoverProvider {
    constructor(private databaseService: DatabaseService) { }

    async provideHover(
        document: vscode.TextDocument,
        position: vscode.Position,
        token: vscode.CancellationToken
    ): Promise<vscode.Hover | null> {
        // Get the word at the current position
        const wordRange = document.getWordRangeAtPosition(position);
        if (!wordRange) {
            return null;
        }

        const word = document.getText(wordRange);
        if (!word) {
            return null;
        }

        // Get the current file path
        const filePath = document.uri.fsPath;

        // Try to find a member with this name in the database
        const member = await this.databaseService.getMemberByNameAndFile(word, filePath);
        if (!member) {
            // Try getting all members from this file and do a fuzzy match
            const members = await this.databaseService.getMembersByFile(filePath);
            const matchedMember = members.find(m =>
                m.name.includes(word) || word.includes(m.name) || this.fuzzyMatch(m.name, word)
            );

            if (!matchedMember) {
                return null;
            }

            return this.createHover(matchedMember);
        }

        return this.createHover(member);
    }

    private fuzzyMatch(memberName: string, word: string): boolean {
        // Remove common prefixes/suffixes and compare
        const cleanMemberName = memberName.replace(/^(Get|Set|Is|Has|Can)/, '').toLowerCase();
        const cleanWord = word.toLowerCase();

        return cleanMemberName.includes(cleanWord) || cleanWord.includes(cleanMemberName);
    }

    private createHover(member: any): vscode.Hover {
        const markdown = new vscode.MarkdownString();
        markdown.isTrusted = true;
        markdown.supportHtml = true;

        // Add member type icon
        const icon = this.getIconForType(member.type);
        markdown.appendMarkdown(`### ${icon} \`${member.name}\`\n\n`);
        markdown.appendMarkdown(`**Type:** ${member.type}\n\n`);
        markdown.appendMarkdown(`**Summary:** ${member.summary}\n\n`);
        markdown.appendMarkdown(`---\n\n`);
        markdown.appendMarkdown(`*AI-generated by SourceCode Summariser*`);

        return new vscode.Hover(markdown);
    }

    private getIconForType(type: string): string {
        switch (type.toLowerCase()) {
            case 'method':
                return '⚙️';
            case 'class':
                return '📦';
            case 'interface':
                return '🔌';
            case 'property':
                return '🔧';
            case 'field':
                return '📊';
            case 'struct':
                return '🏗️';
            case 'namespace':
                return '📁';
            default:
                return '📄';
        }
    }
}
